dvine/app_core/urls.py
from django.urls import path
from app_core.views import general

app_name = 'app_core'
urlpatterns = [
    path('', general.index, name='index'),
    path('about/', general.about, name='about'),
    path('services/<int:pk>/', general.services_view, name='services_view'),
    path('works/', general.works, name='works'),
    path('faq/', general.faq, name='faq'),
    path('contact/', general.contact, name='contact'),
    path('privacy/', general.privacy, name='privacy'),
    path('mail/', general.mail_view, name='mail'),
]

dvine/dvine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include('app_core.urls', namespace='app_core')),
    path('', include('app_user.urls', namespace='app_user')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dvine/app_core/forms.py
from django import forms
from app_core.models import Contact, Banner, About, Skill, Counter, Service, SubService, Testimonial, Partner, Faq, Privacy, WorkImage, SocialMedia

SOCIAL_MEDIA_CHOICES = [
    ('01', 'Facebook'),
    ('02', 'Twitter'),
    ('03', 'Instagram'),
    ('04', 'TikTok'),
    ('05', 'YouTube'),
    ('06', 'LinkedIn'),
]

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['location', 'phone1', 'phone2', 'email', 'latitude', 'longitude']
        widgets = {
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'phone1': forms.TextInput(attrs={'class': 'form-control'}),
            'phone2': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'type': 'email'}),
            'latitude': forms.NumberInput(attrs={'class': 'form-control', 'type': 'number' }),
            'longitude': forms.NumberInput(attrs={'class': 'form-control', 'type': 'number'}),
        }

class BannerForm(forms.ModelForm):
    class Meta:
        model = Banner
        fields = ['image', 'title', 'subtitle', 'description', 'insurance']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'subtitle': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'resizable_textarea form-control'}),
            'insurance': forms.TextInput(attrs={'class': 'form-control'}),
        }

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = ['image', 'about', 'mision', 'vision', 'image_google', 'url_google']
        widgets = {
            'url_google': forms.TextInput(attrs={'class': 'fom-rcontrol', 'type': 'url'}),
        }

class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['title1', 'description1', 'title2', 'description2', 'title3', 'description3']
        widgets = {
            'title1': forms.TextInput(attrs={'class': 'form-control'}),
            'description1': forms.Textarea(attrs={'class': 'resizable_textarea form-control'}),
            'title2': forms.TextInput(attrs={'class': 'form-control'}),
            'description2': forms.Textarea(attrs={'class': 'resizable_textarea form-control'}),
            'title3': forms.TextInput(attrs={'class': 'form-control'}),
            'description3': forms.Textarea(attrs={'class': 'resizable_textarea form-control'}),
        }

class CounterForm(forms.ModelForm):
    class Meta:
        model = Counter
        fields = ['title1', 'number1', 'title2', 'number2', 'title3', 'number3']
        widgets = {
            'title1': forms.TextInput(attrs={'class': 'form-control'}),
            'number1': forms.NumberInput(attrs={'class': 'form-control', 'type': 'number'}),
            'title2': forms.TextInput(attrs={'class': 'form-control'}),
            'number2': forms.NumberInput(attrs={'class': 'form-control', 'type': 'number'}),
            'title3': forms.TextInput(attrs={'class': 'form-control'}),
            'number3': forms.NumberInput(attrs={'class': 'form-control', 'type': 'number'}),
        }

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['image', 'title', 'description', 'description_finish']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description_finish': forms.Textarea(attrs={'class': 'resizable_textarea form-control'}),
        }

class ServiceDeleteForm(forms.Form):
    id_to_delete = forms.IntegerField(widget=forms.HiddenInput())

class SubServiceForm(forms.ModelForm):
    class Meta:
        model = SubService
        fields = ['service', 'image', 'title', 'description']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
        }

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ['image', 'name', 'location', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'resizable_textarea form-control'}),
        }

class TestimonialDeleteForm(forms.Form):
    id_to_delete = forms.IntegerField(widget=forms.HiddenInput())

class PartnerForm(forms.ModelForm):
    class Meta:
        model = Partner
        fields = ['image', 'url']
        widgets = {
            'url': forms.TextInput(attrs={'class': 'fom-rcontrol', 'type': 'url'}),
        }

class FaqForm(forms.ModelForm):
    class Meta:
        model = Faq
        fields = ['title', 'description']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
        }

class PrivacyForm(forms.ModelForm):
    class Meta:
        model = Privacy
        fields = ['title', 'description']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
        }

class WorkForm(forms.ModelForm):
    class Meta:
        model = WorkImage
        fields = ['image']

class SocialMediaForm(forms.ModelForm):
    name = forms.ChoiceField(choices=SOCIAL_MEDIA_CHOICES, label='Name', required=True)
    class Meta:
        model = SocialMedia
        fields = ['name', 'url']
        widgets = {
            'name': forms.Select(attrs={'class': 'form-control'}),
            'url': forms.TextInput(attrs={'class': 'fom-rcontrol', 'type': 'url'}),
        }

dvine/app_core/views/general.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from app_core.models import Contact, Banner, About, Skill, Counter, Service, SubService, WorkImage, Testimonial, \
    Partner, Faq, Privacy, SocialMedia


def index(request):
    contact = Contact.objects.all().last()
    banner = Banner.objects.all().last()
    about = About.objects.all().last()
    skills = Skill.objects.all().last()
    indicators = Counter.objects.all().last()
    servicios = Service.objects.all()
    works = WorkImage.objects.all().order_by('?')[:6]
    testimonials = Testimonial.objects.all()
    partners = Partner.objects.all()
    social_media = SocialMedia.objects.all()
    context = {
        'contact': contact,
        'banner': banner,
        'about': about,
        'skills': skills,
        'indicators': indicators,
        'servicios': servicios,
        'works': works,
        'testimonials': testimonials,
        'partners': partners,
        'social_media': social_media
    }

    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            username = request.POST.get('userName')
            company = request.POST.get('companyName')
            email = request.POST.get('email')

            # y enviar el correo electrónico correspondiente
            send_msg_stay_connected(username, company, email)
            return render(request, 'app_core/pages/index.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/index.html', context)


def about(request):
    contact = Contact.objects.all().last()
    about = About.objects.all().last()
    skills = Skill.objects.all().last()
    servicios = Service.objects.all()
    indicators = Counter.objects.all().last()
    testimonials = Testimonial.objects.all()
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    context = {
        'contact': contact,
        'servicios': servicios,
        'about': about,
        'indicators': indicators,
        'skills': skills,
        'testimonials': testimonials,
        'works': works,
        'social_media': social_media
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            username = request.POST.get('userName')
            company = request.POST.get('companyName')
            email = request.POST.get('email')

            # y enviar el correo electrónico correspondiente
            send_msg_stay_connected(username, company, email)
            return render(request, 'app_core/pages/about.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/about.html', context)


def services(request):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    context = {
        'contact': contact,
        'servicios': servicios,
        'works': works,
        'social_media': social_media
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            username = request.POST.get('userName')
            company = request.POST.get('companyName')
            email = request.POST.get('email')

            # y enviar el correo electrónico correspondiente
            send_msg_stay_connected(username, company, email)
            return render(request, 'app_core/pages/services.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/services.html', context)


def services_view(request, pk):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    servicio = Service.objects.get(pk=pk)
    subservicios = SubService.objects.filter(service=pk)
    works = WorkImage.objects.all().order_by('?')[:1]
    social_media = SocialMedia.objects.all()
    context = {
        'contact': contact,
        'servicio': servicio,
        'servicios': servicios,
        'subservicios': subservicios,
        'works': works,
        'social_media': social_media
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            username = request.POST.get('userName')
            company = request.POST.get('companyName')
            email = request.POST.get('email')

            # y enviar el correo electrónico correspondiente
            send_msg_stay_connected(username, company, email)
            return render(request, 'app_core/pages/service.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/service.html', context)


def works(request):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    gallery = WorkImage.objects.all().order_by('?')
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    context = {
        'contact': contact,
        'servicios': servicios,
        'gallery': gallery,
        'works': works,
        'social_media': social_media
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            username = request.POST.get('userName')
            company = request.POST.get('companyName')
            email = request.POST.get('email')

            # y enviar el correo electrónico correspondiente
            send_msg_stay_connected(username, company, email)
            return render(request, 'app_core/pages/works.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/works.html', context)


def faq(request):
    contact = Contact.objects.all().last()
    faqs = Faq.objects.all()
    servicios = Service.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    social_media = SocialMedia.objects.all()
    context = {
        'contact': contact,
        'servicios': servicios,
        'faqs': faqs,
        'social_media': social_media,
        'works': works
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            username = request.POST.get('userName')
            company = request.POST.get('companyName')
            email = request.POST.get('email')

            # y enviar el correo electrónico correspondiente
            send_msg_stay_connected(username, company, email)
            return render(request, 'app_core/pages/faq.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/faq.html', context)


def contact(request):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    testimonials = Testimonial.objects.all()
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    context = {
        'servicios': servicios,
        'contact': contact,
        'testimonials': testimonials,
        'social_media': social_media,
        'works': works
    }
    if request.method == 'POST':
        print(f"Veamos si entra en el metyhod post")
        if 'stay_connected' in request.POST:
            username = request.POST.get('userName')
            company = request.POST.get('companyName')
            email = request.POST.get('email')

            # y enviar el correo electrónico correspondiente
            send_msg_stay_connected(username, company, email)
            return render(request, 'app_core/pages/contact.html', context)
        elif 'contact_us_form' in request.POST:
            print(f"Veweamos si entyra aqui boton de contact us form")
            username = request.POST.get('userName')
            message = request.POST.get('userMessage')
            email = request.POST.get('userEmail')

            # y enviar el correo electrónico correspondiente
            send_msg_contact_us(username, message, email)
            print(f"En este momentro el mensaje yua se envio")
            return render(request, 'app_core/pages/contact.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/contact.html', context)


def privacy(request):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    privacy = Privacy.objects.all().last()
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    context = {
        'contact': contact,
        'servicios': servicios,
        'privacy': privacy,
        'social_media': social_media,
        'works': works
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            username = request.POST.get('userName')
            company = request.POST.get('companyName')
            email = request.POST.get('email')

            # y enviar el correo electrónico correspondiente
            send_msg_stay_connected(username, company, email)
            return render(request, 'app_core/pages/privacy.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/privacy.html', context)


def send_msg_stay_connected(username, company, email):
    subject = 'Stay Connected M2J'
    message = f'Hello, M2J you have a new subscriber: \nUsername: {username} \nCompany: {company} \nEmail: {email}.'
    from_email = 'ideafix.mensajeria@gmail.com'
    recipient_list = ['libardoentrenandolatinos@gmail.com']
    send_mail(subject, message, from_email, recipient_list)


def send_msg_contact_us(username, get_message, email):
    subject = 'Contact Us M2J'
    message = f'Hello, M2J you have a new message: \nUsername: {username} \nMessage: {get_message} \nEmail: {email}.'
    from_email = 'ideafix.mensajeria@gmail.com'

dvine/templates/app_core/snippets/banner_about.html
{% load static %}

<!-- Hero -->
<section id="slider" class="hero p-0 odd featured">
    <div class="swiper-container no-slider slider-h-75">
        <div class="swiper-wrapper">

            <!-- Item 1 -->
            <div class="swiper-slide slide-center">
                
                <img src="{% static 'app_core/assets/images/Banner_secciones.webp' %}" class="full-image" data-mask="70">
                
                <div class="slide-content row text-center">
                    <div class="col-12 mx-auto inner">
                        <h1 data-aos="zoom-out-up" data-aos-delay="400" class="title effect-static-text">About</h1>
                        <a id="whatsapp_banner_web" style="background-color: #25d366; color: white;" data-aos="zoom-out-up" data-aos-delay="600" class="ml-auto mr-auto mt-5 btn" target="_blank" href="https://web.whatsapp.com/send?l=es&phone=1{{contact.phone1}}&text=https://dvineroofingllc.com/ " rel="noopener noreferrer">
                            <i class="whatsapp-icon"></i> Whatsapp 
                        </a>
                        <a id="whatsapp_banner_movil" style="background-color: #25d366; color: white;" data-aos="zoom-out-up" data-aos-delay="600" class="ml-auto mr-auto mt-5 btn" target="_blank" href="https://api.whatsapp.com/send?l=es&phone=1{{contact.phone1}}&text=https://dvineroofingllc.com/ " rel="noopener noreferrer">
                            <i class="whatsapp-icon"></i> Whatsapp
                        </a>
                        <nav data-aos="zoom-out-up" data-aos-delay="800" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'app_core:index' %}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">About Us</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

dvine/templates/app_core/snippets/banner_faq.html
{% load static %}

<!-- Hero -->
<section id="slider" class="hero p-0 odd featured">
    <div class="swiper-container no-slider slider-h-75">
        <div class="swiper-wrapper">

            <!-- Item 1 -->
            <div class="swiper-slide slide-center">
                
                <img src="{% static 'app_core/assets/images/Banner_secciones.webp' %}" class="full-image" data-mask="70">
                
                <div class="slide-content row text-center">
                    <div class="col-12 mx-auto inner">
                        <h1 data-aos="zoom-out-up" data-aos-delay="400" class="title effect-static-text">FAQ's</h1>
                        <a id="whatsapp_banner_web" style="background-color: #25d366; color: white;" data-aos="zoom-out-up" data-aos-delay="600" class="ml-auto mr-auto mt-5 btn" target="_blank" href="https://web.whatsapp.com/send?l=es&phone=1{{contact.phone1}}&text=https://dvineroofingllc.com/ " rel="noopener noreferrer">
                            <i class="whatsapp-icon"></i> Whatsapp 
                        </a>
                        <a id="whatsapp_banner_movil" style="background-color: #25d366; color: white;" data-aos="zoom-out-up" data-aos-delay="600" class="ml-auto mr-auto mt-5 btn" target="_blank" href="https://api.whatsapp.com/send?l=es&phone=1{{contact.phone1}}&text=https://dvineroofingllc.com/ " rel="noopener noreferrer">
                            <i class="whatsapp-icon"></i> Whatsapp
                        </a>
                        <nav data-aos="zoom-out-up" data-aos-delay="800" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'app_core:index' %}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">FAQ's</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

dvine/templates/app_core/snippets/banner_service.html
{% load static %}

<!-- Hero -->
<section id="slider" class="hero p-0 odd featured">
    <div class="swiper-container no-slider slider-h-75">
        <div class="swiper-wrapper">

            <!-- Item 1 -->
            <div class="swiper-slide slide-center">
                
                <img src="{% static 'app_core/assets/images/Banner_secciones.webp' %}" class="full-image" data-mask="70">
                
                <div class="slide-content row text-center">
                    <div class="col-12 mx-auto inner">
                        <h1 data-aos="zoom-out-up" data-aos-delay="400" class="title effect-static-text">Service Detail</h1>
                        <a id="whatsapp_banner_web" style="background-color: #25d366; color: white;" data-aos="zoom-out-up" data-aos-delay="600" class="ml-auto mr-auto mt-5 btn" target="_blank" href="https://web.whatsapp.com/send?l=es&phone=1{{contact.phone1}}&text=https://dvineroofingllc.com/ " rel="noopener noreferrer">
                            <i class="whatsapp-icon"></i> Whatsapp 
                        </a>
                        <a id="whatsapp_banner_movil" style="background-color: #25d366; color: white;" data-aos="zoom-out-up" data-aos-delay="600" class="ml-auto mr-auto mt-5 btn" target="_blank" href="https://api.whatsapp.com/send?l=es&phone=1{{contact.phone1}}&text=https://dvineroofingllc.com/ " rel="noopener noreferrer">
                            <i class="whatsapp-icon"></i> Whatsapp
                        </a>
                        <nav data-aos="zoom-out-up" data-aos-delay="800" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'app_core:index' %}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Service Detail</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

dvine/templates/app_core/snippets/footer.html
<!-- Footer -->
<footer class="odd">

    <!-- Footer [links] -->
    <section id="footer" class="footer" style="padding: 81px 0;">
        <div class="container">
            <div class="row items footer-widget">
                <div class="col-12 col-lg-3 p-0">
                    <div class="row">
                        <div class="branding col-12 p-3 text-center text-lg-left item">
                            <div class="brand">
                                <a href="/" class="logo">
                                    DVINE                                 
                                    <!-- 
                                        Custom Logo
                                        <img src="assets/images/logo.svg" alt="Leverage">
                                    -->
                                </a>
                            </div>
                            <P>Experience the DVine Roofing LLC difference, where professionalism meets elegance, and your property's well-being is our top priority.</P>
                            <!-- <p>Authentic and innovative.<br>Built to the smallest detail<br>with a focus on usability<br>and performance.</p> -->
                            <ul class="navbar-nav social share-list mt-0 ml-auto">
                            {% for red_social in social_media %}
                            <li class="nav-item">
                                <a href="{{red_social.url}}" class="nav-link" target="_blank"><i class="{{red_social.icon_class_footer}}"></i></a>
                            </li>
                            {% endfor %}
                                <!-- <li class="nav-item">
                                    <a href="#" class="nav-link"><i class="icon-social-instagram ml-0"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link"><i class="icon-social-facebook"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link"><i class="icon-social-linkedin"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link"><i class="icon-social-twitter"></i></a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link"><i class="fab fa-tiktok custom-icon-tiktok-footer"></i> </a>
                                </li> -->
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-9 p-0">                            
                    <div class="row">
                        <div class="col-12 col-lg-4 p-3 text-center text-lg-left item">
                            <h4 class="title">Get in Touch</h4>
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link">
                                        <i class="icon-phone mr-2"></i>
                                        +1 {{contact.phone1}}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link">
                                        <i class="icon-envelope mr-2"></i>
                                        {{contact.email}}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link">
                                        <i class="icon-location-pin mr-2"></i>
                                        {{contact.location}}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'app_core:contact' %}#contact" class="mt-4 mr-auto ml-auto ml-lg-0 btn primary-button"><i class="icon-speech"></i>SEND A MESSAGE</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-12 col-lg-4 p-3 text-center text-lg-left item">
                            <h4 class="title">Our Services</h4>
                            <ul class="navbar-nav">
                                {% for servicio in servicios %}
                                    <li class="nav-item">
                                        <a href="{% url 'app_core:services_view' servicio.id %}" class="nav-link">{{servicio.title}}</a>
                                    </li>    
                                {% endfor %}
                                <!-- <li class="nav-item">
                                    <a href="#" class="nav-link">Website Development</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">Building Applications</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">SEO & Digital Marketing</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">Branding and Identity</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">Digital Images & Videos</a>
                                </li> -->
                            </ul>
                        </div>
                        <div class="col-12 col-lg-4 p-3 text-center text-lg-left item">
                            <h4 class="title">Our Work</h4>
                            {% for work in works|slice:":1" %}
                                <img src="{{work.image.url}}" alt="">
                            {% endfor %}
                            <a href="{% url 'app_core:works' %}" class="mt-4 mr-auto ml-auto ml-lg-0 btn primary-button"><i class="icon-grid"></i>VIEW ALL</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Copyright -->
    <section id="copyright" class="p-3 copyright">
        <div class="container">
            <div class="row">
                <!-- <div class="col-12 col-md-6 p-3 text-center text-lg-left">
                    <p>Enjoy the low price. We are tracking any intention of piracy.</p>
                </div> -->
                <div class="col-12 col-md-6 p-3 text-center text-lg-right">
                    <p>&copy; <script>document.write(new Date().getFullYear())</script> DVINE All rights reserved</p>
                </div>
            </div>
        </div>
    </section>

</footer>

dvine/templates/app_core/snippets/modal_search.html
<!-- Modal [search] -->
<div id="search" class="p-0 modal fade" role="dialog" aria-labelledby="search" aria-hidden="true">
    <div class="modal-dialog modal-dialog-slideout" role="document">
        <div class="modal-content full">
            <div class="modal-header" data-dismiss="modal">
                Search <i class="icon-close"></i>
            </div>
            <div class="modal-body">
                <form class="row">
                    <div class="col-12 p-0 align-self-center">
                        <div class="row">
                            <div class="col-12 p-0 pb-3">
                                <h2>What are you looking for?</h2>
                                <p>Search for services and news about the best that happens in the world.</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 p-0 input-group">
                                <input type="text" class="form-control" placeholder="Enter Keywords">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 p-0 input-group align-self-center">
                                <button class="btn primary-button"><i class="icon-magnifier"></i>SEARCH</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>