dvine/app_user/urls.py
from django.urls import path
from app_user.views import administrator

app_name = 'app_user'

urlpatterns = [
    path(
        'login/redirect/',
        administrator.login_redirect,
        name='login-redirect'
    ),
    path(
        'administrator/index/',
        administrator.admin_index,
        name='admin_index'
    ),
    path(
        'administrator/contact_update/',
        administrator.contact_update,
        name='contact_update'
    ),
    path(
        'administrator/banner_update/',
        administrator.banner_update,
        name='banner_update'
    ),
    path(
        'administrator/about_update/',
        administrator.about_update,
        name='about_update'
    ),
    path(
        'administrator/skill_update/',
        administrator.skill_update,
        name='skill_update'
    ),
    path(
        'administrator/counter_update/',
        administrator.counter_update,
        name='counter_update'
    ),
    path(
        'administrator/services/',
        administrator.services,
        name='services'
    ),
    path(
        'administrator/service_create/',
        administrator.service_create,
        name='service_create'
    ),
    path(
        'administrator/service_update/<int:pk>/',
        administrator.service_update,
        name='service_update'
    ),
    path(
        'administrator/subservices/<int:pk>/',
        administrator.subservices,
        name='subservices'
    ),
    path(
        'administrator/subservice_create/<int:pk>/',
        administrator.subservice_create,
        name='subservice_create'
    ),
    path(
        'administrator/subservice_update/<int:pk>/',
        administrator.subservice_update,
        name='subservice_update'
    ),
    path(
        'administrator/testimonials/',
        administrator.testimonials,
        name='testimonials'
    ),
    path(
        'administrator/testimonials_create/',
        administrator.testimonials_create,
        name='testimonials_create'
    ),
    path(
        'administrator/testimonial_update/<int:pk>/',
        administrator.testimonial_update,
        name='testimonial_update'
    ),
    path(
        'administrator/partners/',
        administrator.partners,
        name='partners'
    ),
    path(
        'administrator/partner_create/',
        administrator.partner_create,
        name='partner_create'
    ),
    path(
        'administrator/partner_update/<int:pk>/',
        administrator.partner_update,
        name='partner_update'
    ),
    path(
        'administrator/faqs/',
        administrator.faqs,
        name='faqs'
    ),
    path(
        'administrator/faq_create/',
        administrator.faq_create,
        name='faq_create'
    ),
    path(
        'administrator/faq_update/<int:pk>/',
        administrator.faq_update,
        name='faq_update'
    ),
    path(
        'administrator/privacy_update/',
        administrator.privacy_update,
        name='privacy_update'
    ),
    path(
        'administrator/works/',
        administrator.works,
        name='works'
    ),
    path(
        'administrator/work_create/',
        administrator.work_create,
        name='work_create'
    ),
    path(
        'administrator/social_media/',
        administrator.social_media,
        name='social_media'
    ),
    path(
        'administrator/social_media_create/',
        administrator.social_media_create,
        name='social_media_create'
    ),
    path(
        'administrator/social_media_update/<int:pk>/',
        administrator.social_media_update,
        name='social_media_update'
    ),
]

dvine/dvine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include('app_core.urls', namespace='app_core')),
    path('', include('app_user.urls', namespace='app_user')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dvine/app_user/models.py
from django.db import models

# Create your models here.

dvine/app_user/views.py
from django.shortcuts import render

# Create your views here.

dvine/app_user/views/administrator.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from app_core.forms import ContactForm, BannerForm, AboutForm, SkillForm, CounterForm, ServiceForm, ServiceDeleteForm, SubServiceForm, TestimonialForm, TestimonialDeleteForm, PartnerForm, FaqForm, PrivacyForm, WorkForm, SocialMediaForm
from app_core.models import Contact, Banner, About, Skill, Counter, Service, SubService, WorkImage, Testimonial, Partner, Faq, Privacy, SocialMedia

def login_redirect(request):
    if request.user.is_superuser:
        return redirect('app_user:admin_index')
    
@login_required
def admin_index(request):
    context = {}
    return render(request, 'app_user/pages/index.html', context)

############### CONTACT INFO ###############
@login_required
def contact_update(request):
    contact = Contact.objects.all().last()

    if request.method == 'POST':
        contact_form = ContactForm(request.POST, request.FILES, instance=contact)
        if contact_form.is_valid():
            contact_form.save()
            return redirect('app_user:admin_index')
    else:
        contact_form = ContactForm(instance=contact)

    context = {'contact':contact, 'contact_form':contact_form}
    return render(request, 'app_user/pages/contact.html', context)

############### BANNER ###############
@login_required
def banner_update(request):
    banner = Banner.objects.all().last()

    if request.method == 'POST':
        banner_form = BannerForm(request.POST, request.FILES, instance=banner)
        if banner_form.is_valid():
            banner_form.save()
            return redirect('app_user:admin_index')
    else:
        banner_form = BannerForm(instance=banner)

    context = {'banner':banner, 'banner_form':banner_form}
    return render(request, 'app_user/pages/banner.html', context)

############### ABOUT ###############
@login_required
def about_update(request):
    about = About.objects.all().last()

    if request.method == 'POST':
        about_form = AboutForm(request.POST, request.FILES, instance=about)
        if about_form.is_valid():
            about_form.save()
            return redirect('app_user:admin_index')
    else:
        about_form = AboutForm(instance=about)

    context = {'about':about, 'about_form':about_form}
    return render(request, 'app_user/pages/about.html', context)

############### WHY US ###############
@login_required
def skill_update(request):
    skill = Skill.objects.all().last()

    if request.method == 'POST':
        skill_form = SkillForm(request.POST, request.FILES, instance=skill)
        if skill_form.is_valid():
            skill_form.save()
            return redirect('app_user:admin_index')
    else:
        skill_form = SkillForm(instance=skill)

    context = {'skill':skill, 'skill_form':skill_form}
    return render(request, 'app_user/pages/skill.html', context)

############### COUNTERS ###############
@login_required
def counter_update(request):
    counter = Counter.objects.all().last()

    if request.method == 'POST':
        counter_form = CounterForm(request.POST, request.FILES, instance=counter)
        if counter_form.is_valid():
            counter_form.save()
            return redirect('app_user:admin_index')
    else:
        counter_form = CounterForm(instance=counter)

    context = {'counter':counter, 'counter_form':counter_form}
    return render(request, 'app_user/pages/counter.html', context)

############### SERVICES ###############
@login_required
def services(request):
    services = Service.objects.all()
    context = {'services':services}
    return render(request, 'app_user/pages/services.html', context)

@login_required
def service_create(request):
    if request.method == 'POST':
        service_form = ServiceForm(request.POST, request.FILES)
        if service_form.is_valid():
            new_service = service_form.save()
            return redirect('app_user:services')
    else:
        service_form = ServiceForm()

    return render(request, 'app_user/pages/service_create.html', {'service_form': service_form})

@login_required
def service_update(request, pk):
    service = get_object_or_404(Service, id=pk)

    if request.method == 'POST':
        if 'update_service' in request.POST:
            service_form = ServiceForm(request.POST, request.FILES, instance=service, prefix='service_update')
            if service_form.is_valid():
                print("Almenos esntramos aqui")
                service_form.save()
                return redirect('app_user:services')
        elif 'delete_service' in request.POST:
            service_delete_form = ServiceDeleteForm(request.POST, prefix='service_delete', initial={'id_to_delete': pk})
            if service_delete_form.is_valid():
                id_to_delete = service_delete_form.cleaned_data['id_to_delete']
                # Eliminar el registro con el id especificado
                Service.objects.filter(id=id_to_delete).delete()
                return redirect('app_user:services')
    else:
        service_form = ServiceForm(instance=service, prefix='service_update')
        service_delete_form = ServiceDeleteForm(prefix='service_delete', initial={'id_to_delete': pk})

    context = {'service':service, 'service_form':service_form, 'service_delete_form':service_delete_form}
    return render(request, 'app_user/pages/service_update.html', context)

############### SUBSERVICES ###############
@login_required
def subservices(request, pk):
    service = get_object_or_404(Service, id=pk)
    subservices = SubService.objects.filter(service=pk)
    
    if request.method == 'POST':
        subservice_id = request.POST.get('deleteSubserviceInput', '')
        SubService.objects.filter(pk=subservice_id).delete()

    context = {'subservices':subservices, 'service':service}
    return render(request, 'app_user/pages/subservices.html', context)

@login_required
def subservice_create(request, pk):
    service = get_object_or_404(Service, id=pk)
    subservices = SubService.objects.filter(service=pk)

    if request.method == 'POST':
        subservice_form = SubServiceForm(request.POST, request.FILES)
        if subservice_form.is_valid():
            new_subservice = subservice_form.save()
            context = {'service':service, 'subservices': subservices}
            return redirect(reverse('app_user:subservices', args=[service.id]), context)
    else:
        subservice_form = SubServiceForm()
        context = {'service':service, 'subservice_form': subservice_form}

    return render(request, 'app_user/pages/subservice_create.html', context)

@login_required
def subservice_update(request, pk):
    subservice = get_object_or_404(SubService, id=pk)
    service = get_object_or_404(Service, service_subservice__id=pk)
    subservices = SubService.objects.filter(service=service.id)

    if request.method == 'POST':
        subservice_form = SubServiceForm(request.POST, request.FILES, instance=subservice)
        if subservice_form.is_valid():
            subservice_form.save()
            context = {'service':service, 'subservices': subservices}
            return redirect(reverse('app_user:subservices', args=[service.id]), context)
        
    else:
        subservice_form = SubServiceForm(instance=subservice)

    context = {'service':service, 'subservice':subservice, 'subservice_form':subservice_form}
    return render(request, 'app_user/pages/subservice_update.html', context)

############### TESTIMONIALS ###############
@login_required
def testimonials(request):
    testimonials = Testimonial.objects.all()
    context = {'testimonials':testimonials}
    return render(request, 'app_user/pages/testimonials.html', context)

@login_required
def testimonials_create(request):
    if request.method == 'POST':
        testimonial_form = TestimonialForm(request.POST, request.FILES)
        if testimonial_form.is_valid():
            new_testimonial = testimonial_form.save()
            return redirect('app_user:testimonials')
    else:
        testimonial_form = TestimonialForm()

    return render(request, 'app_user/pages/testimonials_create.html', {'testimonial_form': testimonial_form})

@login_required
def testimonial_update(request, pk):
    testimonial = get_object_or_404(Testimonial, id=pk)

    if request.method == 'POST':
        if 'update_testimonial' in request.POST:
            testimonial_form = TestimonialForm(request.POST, request.FILES, instance=testimonial, prefix='testimonial_update')
            
            if testimonial_form.is_valid():
                testimonial_form.save()
                return redirect('app_user:testimonials')
        
        elif 'delete_testimonial' in request.POST:
            testimonial_delete_form = TestimonialDeleteForm(request.POST, prefix='testimonial_delete', initial={'id_to_delete': pk})
            if testimonial_delete_form.is_valid():
                id_to_delete = testimonial_delete_form.cleaned_data['id_to_delete']
                # Eliminar el registro con el id especificado
                Testimonial.objects.filter(id=id_to_delete).delete()
                return redirect('app_user:testimonials')
    else:
        testimonial_form = TestimonialForm(instance=testimonial, prefix='testimonial_update')
        testimonial_delete_form = TestimonialDeleteForm(prefix='testimonial_delete', initial={'id_to_delete': pk})

    context = {'testimonial':testimonial, 'testimonial_form':testimonial_form, 'testimonial_delete_form':testimonial_delete_form}
    return render(request, 'app_user/pages/testimonial_update.html', context)

############### PARTNERS ###############
@login_required
def partners(request):
    partners = Partner.objects.all()

    if request.method == 'POST':
        partner_id = request.POST.get('deletePartnerInput', '')
        Partner.objects.filter(pk=partner_id).delete()

    context = {'partners':partners}

dvine/templates/app_user/snippets/footer.html
<!-- footer content -->
<footer>
  <div class="pull-right">
    &copy; <script>document.write(new Date().getFullYear())</script> DVINE All rights reserved
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

dvine/templates/app_user/snippets/index.html
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Dashboard</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="top_tiles">

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:about_update' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-institution icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">About</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:banner_update' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-laptop icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Banner</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:contact_update' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-user icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Contact</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:counter_update' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-area-chart icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Counter</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:faqs' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-check-square-o icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">FAQ</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:partners' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-bolt icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Partner</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:privacy_update' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-file icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Privacy</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:services' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-sitemap icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Services</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:social_media' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-facebook icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Social Media</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:testimonials' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-comment icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Testimonial</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:skill_update' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-cogs icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Why Us</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:works' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-image icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Works</h3>
                            </div>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>
</div>

dvine/templates/app_user/snippets/partners.html
{% load static %}

<div class="">
    <div class="page-title">
        <div class="title_left" style="padding-bottom: 12px;">
            <h3> Partners <small></small> </h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>List <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <a href="{% url 'app_user:partner_create' %}" type="button" class="btn btn-info" style="color: white;">Add Partner</a>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="partnerTable">
                        <thead>
                            <tr>
                                <th style="width: 70%;">Image</th>
                                <th style="width: 30%;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for partner in partners %}
                            <tr>
                                <td>
                                {% if partner.image  %}
                                    <img style="width: 12%; display: block;" src="{{ partner.image.url }}" alt="image" />
                                {% else %}
                                    <img style="width: 12%; display: block;" src="{% static 'app_core/construction/images/logo-1.png' %}" alt="image">
                                {% endif %}
                                </td>
                                <td>
                                    <a class="btn btn-success" href="{% url 'app_user:partner_update' partner.id %}">Update</a>
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deletePartner{{ forloop.counter }}">Delete</button>
                                </td>
                            </tr>
                            <!-- start FAQ's delete modal -->
                                {% include 'app_user/snippets/partner_delete_modal.html' %}
                            <!-- end FAQ's -->
                        {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th style="width: 70%;">Image</th>
                                <th style="width: 30%;">Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>